### ISSUE TITLE
Heading links based on identifier

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvespace#13]
Have a "link" icon on hover over heading targets.

![image](https://user-images.githubusercontent.com/913249/162019481-2caead9d-2e36-4deb-985f-b3f63f193512.png)

This is an anchor `` <a href={`#${node.identifier}`}> <LinkIcon> ....``

**Comment by Yxwww** [comment]
- [ ] show up on hover
- [ ] verify if remix has problem with it
  - scroll to position need to work with `#url`

**Comment by Yxwww** [comment]
- [ ] myst util change: curvenote/myst-util-to-react/pull/3 merged
- [ ] creates PR to consume  myst util changes
