### ISSUE TITLE
Section numbers (turn on)

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvespace#15]
Sections should follow the same number / numbered pattern that we have going in #7, this should link in with heading links in #13.

![image](https://user-images.githubusercontent.com/913249/162022297-1f31271d-6028-4f96-847a-64063c4585bd.png)

The number "3.4" can be put in front of the Heading text:

**Comment by Yxwww** [comment]
## TODO
- [ ] user-select: none on that portion
- [ ] @rowanc1  mentions trailing dot should be part of myst translation instead of frontend rendering
