### ISSUE TITLE
Fix scroll on long titles / break long titles

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvespace#25]
reproduced here: https://transform.softwareunderground.org/2021-practical-python

![6lEfbYxhi1](https://user-images.githubusercontent.com/1473646/162442856-59d99083-561e-4839-90f7-bef5ef6784cf.gif)

**Comment by rowanc1** [comment]
I think this should be done with break-word rather than ellipsis overflow. The whole title is still important and often does not fit on one line:

e.g.
`overflow-wrap: break-word;`

![image](https://user-images.githubusercontent.com/913249/164073668-67266d16-e727-4f51-bec9-16ee857f0005.png)

**Comment by stevejpurves** [comment]
@Yxwww where are we on this one? I saw some ellipsis overflow added somewhere (was that here?) but break word is better we do want to see the whole title.
