### ISSUE TITLE
pandas tables in articles overflow the page

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvespace#84]
from the la palma / Interactive plots article

![Image](https://user-images.githubusercontent.com/1473646/174052010-5afb3dbb-db59-4fe5-a811-1f033a00ea64.png)

**Comment by fwkoch** [comment]
This one starts as `pandas` output from jupyter; however the output cell is just an html table: https://api.curvenote.com/blocks/1Bk7uPlcMuaTyKEshESj/LzUwSyPpw6OHFawe4lkV/versions/1

When we walk the article we grab the article state from this HTML directly: https://github.com/curvenote/curvenotejs/blob/main/src/export/utils/walkArticle.ts#L171

That gives us a prosemirror table which gets converted to a `list-table` directive when markdown is written and a mdast table on web build.

Probably what we want to do is just keep the original HTML and pass that through all the way.

**Comment by fwkoch** [comment]
In fact, just commenting out this chunk mostly fixes it: https://github.com/curvenote/curvenotejs/blob/4d736359c127ce06afd85cb9b7aa2cfa275314c7/src/export/utils/walkArticle.ts#L171-L175

Before: 
![image](https://user-images.githubusercontent.com/9453731/174354318-d7384b13-355a-49f5-a96c-94558197137a.png)

After (with code commented out):
![image](https://user-images.githubusercontent.com/9453731/174354532-2d70c126-67dd-4864-9f98-5b3b02e775be.png)

Not sure if there are more implications to removing that... but seems like it might be for the best...?

**Comment by fwkoch** [comment]
Also - it no longer overflows the page. However, it is cut off and isn't scrollable.

**Comment by stevejpurves** [comment]
I think that is better, preserving rhebpandas styling which is configurable from the notebook is angood solution

**Comment by stevejpurves** [comment]
The truncation has a separate ticket annd actually affevts all outputs, altjough some seem to get scrolllbars, planningnon addressjng that separately.

**Comment by rowanc1** [comment]
We do need that chunk for the latex/word output though!

**Comment by stevejpurves** [comment]
ah yes, we do need that for pdf/docx targets but for web targets we should disable. @fwkoch this is one of the situations where `walkArticle` needs to diverge
